# Generated by Django 5.2.4 on 2025-07-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_per', models.FloatField()),
                ('unit_of_measurement', models.CharField(choices=[('шт', 'Штуки'), ('м2', 'Квадратные метры')], max_length=10)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='FinishedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('connection', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('price_per', models.FloatField()),
                ('unit_of_measurement', models.CharField(choices=[('шт', 'Штуки'), ('м2', 'Квадратные метры')], max_length=10)),
            ],
            options={
                'verbose_name': 'Finished Product',
                'verbose_name_plural': 'Finished Products',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('price_per', models.FloatField()),
                ('unit_of_measurement', models.CharField(choices=[('шт', 'Штуки'), ('м2', 'Квадратные метры')], max_length=10)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='EquipmentToProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.equipment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Equipment to Project',
                'verbose_name_plural': 'Equipment to Projects',
            },
        ),
        migrations.CreateModel(
            name='FinishedProductToProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.finishedproducts')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Finished Product to Project',
                'verbose_name_plural': 'Finished Products to Projects',
            },
        ),
        migrations.CreateModel(
            name='ServiceToProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.services')),
            ],
            options={
                'verbose_name': 'Service to Project',
                'verbose_name_plural': 'Services to Projects',
            },
        ),
    ]
